"""Add auth + records

Revision ID: 0a398c9d2fac
Revises: 
Create Date: 2025-08-08 21:50:36.636742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a398c9d2fac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_attempts')
    with op.batch_alter_table('fraud_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fraud_records_scenario'))

    op.drop_table('fraud_records')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fraud_records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('scenario', sa.VARCHAR(length=64), nullable=False),
    sa.Column('label', sa.VARCHAR(length=16), nullable=False),
    sa.Column('score', sa.FLOAT(), nullable=False),
    sa.Column('explanation', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fraud_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fraud_records_scenario'), ['scenario'], unique=False)

    op.create_table('quiz_attempts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('score', sa.INTEGER(), nullable=False),
    sa.Column('total', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
